// ==================== Radar Adapter Types ====================
// 统一的数据源适配器接口定义

// MongoDB enums defined locally (not generated by Prisma)
export type ChannelType = 'TENDER' | 'MAPS' | 'DIRECTORY' | 'TRADESHOW' | 'HIRING' | 'ECOSYSTEM' | 'CUSTOM' | 'SOCIAL';
export type AdapterType = 'API' | 'RSS' | 'AI_SEARCH' | 'CSV_IMPORT' | 'MANUAL';

// ==================== Discovery Source Categories ====================

export type SourceCategory =
  | 'web_serp_english'
  | 'web_serp_local_language'
  | 'exa_semantic'
  | 'hiring_signal'
  | 'expansion_news'
  | 'environmental_permit'
  | 'factory_video'
  | 'industrial_directory'
  | 'social_serp_facebook'
  | 'social_serp_linkedin'
  | 'manual_social_seed'
  | 'apollo_enrichment'
  | 'places_validation';
export type RadarStoragePolicy = 'ID_ONLY' | 'TTL_CACHE' | 'SNAPSHOT_IMPORT';

// ==================== 数据源类型标注 ====================

/**
 * 数据源类型
 * 
 * OFFICIAL_API: 官方API，有明确的API文档和认证方式
 * - 示例：TED, SAM.gov, Google Places
 * - 数据质量：高，直接来自源头
 * - 需要认证：通常需要
 * 
 * PUBLIC_DATA: 公开数据，无需认证即可访问
 * - 示例：UNGM公开端点, 政府网站RSS
 * - 数据质量：高
 * - 需要认证：否
 * 
 * WEB_SCRAPING: 网页抓取，从公开网页提取数据
 * - 示例：政府采购网站、展会参展商列表
 * - 数据质量：中等，取决于网页结构
 * - 需要认证：否
 * 
 * AI_INFERRED: AI推断，通过搜索引擎+AI分析获取
 * - 示例：新兴市场采购、海关数据、招聘信号
 * - 数据质量：不稳定，可能存在幻觉
 * - 需要认证：搜索引擎API Key
 */
export type SourceDataType = 'OFFICIAL_API' | 'PUBLIC_DATA' | 'WEB_SCRAPING' | 'AI_INFERRED';

/**
 * 数据质量等级
 */
export type DataQualityLevel = 'HIGH' | 'MEDIUM' | 'LOW' | 'UNSTABLE';

/**
 * 数据源可靠性描述
 */
export interface SourceReliability {
  /** 数据源类型 */
  dataType: SourceDataType;
  /** 数据质量等级 */
  qualityLevel: DataQualityLevel;
  /** 是否需要认证 */
  requiresAuth: boolean;
  /** 认证方式描述 */
  authMethod?: string;
  /** 数据更新频率 */
  updateFrequency?: 'REAL_TIME' | 'DAILY' | 'WEEKLY' | 'UNKNOWN';
  /** 覆盖范围描述 */
  coverageNote?: string;
  /** 已知限制 */
  limitations?: string[];
  /** 官方文档链接 */
  docUrl?: string;
}

// ==================== 适配器能力 ====================

export interface AdapterFeatures {
  supportsKeywordSearch: boolean;
  supportsCategoryFilter: boolean;  // CPV/UNSPSC codes
  supportsDateFilter: boolean;
  supportsRegionFilter: boolean;
  supportsPagination: boolean;
  supportsDetails: boolean;  // 是否支持按需获取详情
  maxResultsPerQuery: number;
  rateLimit: { requests: number; windowMs: number };
}

// ==================== 搜索查询 ====================

export interface RadarSearchQuery {
  keywords?: string[];
  categories?: string[];  // CPV/UNSPSC codes
  countries?: string[];   // ISO codes
  regions?: string[];     // EU | LATAM | MENA | APAC
  publishedAfter?: Date;
  publishedBefore?: Date;
  deadlineAfter?: Date;
  deadlineBefore?: Date;
  page?: number;
  pageSize?: number;
  // AI 搜索专用
  targetIndustries?: string[];
  companyTypes?: string[];  // manufacturer | distributor | service_provider
  locationBias?: { lat: number; lng: number; radius: number };
  // === 过滤 ===
  excludeDomains?: string[];   // 排除的域名
  excludeKeywords?: string[];  // 排除含有这些词的结果
  // === 持续扫描游标 ===
  cursor?: {
    nextPage?: number;
    nextPageToken?: string;
    since?: string;        // ISO8601
    queryIndex?: number;
    planVersion?: string;  // Query plan hash for cursor stability
  };
  maxResults?: number;     // 本次最多抓取条数
  // === Query Planner 输出 ===
  rawQueryText?: string;        // Pre-built query from planner; adapter uses directly
  plannedQueryMeta?: {
    language: string;
    sourceCategory: SourceCategory;
    intent: 'discovery' | 'trigger' | 'competitor' | 'verification';
    planVersion: string;
  };
}

// ==================== 搜索结果 ====================

export interface RadarSearchResult {
  items: NormalizedCandidate[];
  total: number;
  hasMore: boolean;
  nextPage?: number;
  metadata: {
    source: string;
    query: RadarSearchQuery;
    fetchedAt: Date;
    duration: number;
    // 扩展属性
    [key: string]: unknown;
  };
  // === 持续扫描游标 ===
  nextCursor?: {
    nextPage?: number;
    nextPageToken?: string;
    since?: string;        // ISO8601
    queryIndex?: number;
  };
  isExhausted?: boolean;   // 该查询维度已无更多数据
}

// ==================== 标准化候选 ====================

export interface NormalizedCandidate {
  // 必须字段
  externalId: string;
  sourceUrl: string;
  displayName: string;
  candidateType: 'COMPANY' | 'OPPORTUNITY' | 'CONTACT';
  
  // 通用可选字段
  description?: string;
  
  // 公司字段
  website?: string;
  phone?: string;
  email?: string;
  address?: string;
  country?: string;
  city?: string;
  industry?: string;
  companySize?: string;
  
  // 机会/招标字段
  deadline?: Date;
  estimatedValue?: number;
  currency?: string;
  buyerName?: string;
  buyerCountry?: string;
  buyerType?: 'government' | 'enterprise' | 'ngo' | 'international_org';
  categoryCode?: string;
  categoryName?: string;
  publishedAt?: Date;
  contactEmail?: string;
  
  // 联系人字段
  contactRole?: string;
  linkedCompanyExternalId?: string;
  
  // 匹配信息
  matchExplain?: {
    query?: string;
    channel?: string;
    reasons?: string[];
    matchedKeywords?: string[];
    // 适配器特定字段
    jobTitles?: string[];
    importProducts?: string[];
    showName?: string;
    suppliers?: string[];
    products?: string[];
  };
  
  // 匹配分数
  matchScore?: number;
  
  // 原始数据
  rawData?: Record<string, unknown>;
}

// ==================== 详情补全结果 ====================

export interface CandidateDetails {
  externalId: string;
  phone?: string;
  email?: string;
  website?: string;
  address?: string;
  description?: string;
  additionalInfo?: Record<string, unknown>;
}

// ==================== 健康检查结果 ====================

export interface HealthStatus {
  healthy: boolean;
  latency: number;
  error?: string;
  message?: string;  // 添加 message 字段
  lastCheckedAt?: Date;
}

// ==================== 适配器接口 ====================

export interface RadarAdapter {
  readonly sourceCode: string;
  readonly channelType: ChannelType;
  readonly supportedFeatures: AdapterFeatures;
  
  /**
   * 搜索候选
   */
  search(query: RadarSearchQuery): Promise<RadarSearchResult>;
  
  /**
   * 获取详情（可选，用于按需补全）
   */
  getDetails?(externalId: string): Promise<CandidateDetails | null>;
  
  /**
   * 标准化原始数据
   */
  normalize(raw: unknown): NormalizedCandidate;
  
  /**
   * 健康检查
   */
  healthCheck(): Promise<HealthStatus>;
}

// ==================== 适配器配置 ====================

export interface AdapterConfig {
  apiKey?: string;
  apiEndpoint?: string;
  fieldMapping?: Record<string, string>;
  headers?: Record<string, string>;
  timeout?: number;
  retryConfig?: {
    maxRetries: number;
    retryDelay: number;
  };
  // 适配器特定配置
  banks?: string[];      // 开发银行适配器
  regions?: string[];    // 新兴市场适配器
  countries?: string[];  // 国家过滤
  clientId?: string;     // UNGM OAuth
  clientSecret?: string; // UNGM OAuth
  // Configurable identity (for BraveSearchAdapter reuse as social SERP)
  sourceCode?: string;        // Override adapter sourceCode
  channelType?: string;       // Override adapter channelType
  queryPrefix?: string;       // Prepend to every query (e.g., "site:facebook.com")
  parsePromptOverride?: string; // Override AI parse system prompt
}

// ==================== 适配器注册信息 ====================

export interface AdapterRegistration {
  code: string;
  name: string;
  channelType: ChannelType;
  adapterType: AdapterType;
  description: string;
  features: AdapterFeatures;
  defaultConfig: AdapterConfig;
  storagePolicy: RadarStoragePolicy;
  ttlDays: number;
  attributionRequired: boolean;
  countries?: string[];
  regions?: string[];
  isOfficial: boolean;
  websiteUrl?: string;
  termsUrl?: string;
  // === 数据源可靠性标注 ===
  reliability: SourceReliability;
}

// ==================== 适配器工厂 ====================

export type AdapterFactory = (config: AdapterConfig) => RadarAdapter;

// ==================== Structured Discovery Evidence ====================

export interface DiscoveryEvidence {
  _v: 2;

  // Source provenance
  sourceCategory: SourceCategory;
  adapterCode: string;

  // Query context
  queryText: string;
  queryLanguage: string;
  queryCountry: string;
  queryIntent: 'discovery' | 'trigger' | 'competitor' | 'verification';

  // Term matching
  matchedPositiveTerms: string[];
  matchedWeakTerms: string[];
  matchedExclusionTerms: string[];

  // Fast score breakdown
  scoreBreakdown: {
    processSignal: number;
    industryFit: number;
    objectFit: number;
    regionFit: number;
    companyScale: number;
    painTrigger: number;
    penalty: number;
    total: number;
    tier: 'A' | 'B' | 'C' | 'needs_review' | 'reject';
    shouldDeepQualify: boolean;
    reason: string;
  };

  // Metadata
  confidence: number;
  fitScore: number;
  evidenceConfidence: number;
  eligibilityGate: 'QUALIFIED_FOR_SCORING' | 'VERIFY_PROCESS' | 'HARD_REJECT';
  processSignalStrength: 'strong' | 'medium' | 'inferred' | 'none';
  matchedObjectTerms: string[];
  verificationActions: string[];
  enrichmentStatus: 'pending' | 'enriched' | 'failed';
  planVersion?: string;
}

export function isStructuredEvidence(obj: unknown): obj is DiscoveryEvidence {
  return obj !== null && typeof obj === 'object' && '_v' in obj && (obj as { _v: unknown })._v === 2;
}

// ==================== Adapter Error ====================

/** 适配器错误分类 */
export type AdapterErrorCategory =
  | 'AUTH'           // 认证失败（401/403）
  | 'RATE_LIMIT'     // 触发限流（429）
  | 'NETWORK'        // 网络错误（超时、连接失败）
  | 'INVALID_INPUT'  // 输入参数错误
  | 'UPSTREAM'       // 上游 API 返回异常
  | 'INTERNAL';      // 适配器内部错误

/** 适配器统一错误类 */
export class AdapterError extends Error {
  readonly category: AdapterErrorCategory;
  readonly adapterCode: string;
  readonly statusCode?: number;
  readonly retryable: boolean;

  constructor(opts: {
    message: string;
    category: AdapterErrorCategory;
    adapterCode: string;
    statusCode?: number;
    cause?: unknown;
  }) {
    super(opts.message);
    this.name = 'AdapterError';
    this.category = opts.category;
    this.adapterCode = opts.adapterCode;
    this.statusCode = opts.statusCode;
    this.retryable = opts.category === 'RATE_LIMIT' || opts.category === 'NETWORK';
    if (opts.cause) {
      (this as Error & { cause: unknown }).cause = opts.cause;
    }
  }
}

// ==================== Rate Limiter ====================

/** 简易令牌桶限流器（每个适配器独立） */
export class RateLimiter {
  private tokens: number;
  private lastRefill: number;

  constructor(
    private readonly maxRequests: number,
    private readonly windowMs: number,
  ) {
    this.tokens = maxRequests;
    this.lastRefill = Date.now();
  }

  /** 尝试获取一个令牌，返回是否允许 */
  tryAcquire(): boolean {
    this.refill();
    if (this.tokens > 0) {
      this.tokens--;
      return true;
    }
    return false;
  }

  /** 等待直到获取到令牌（带超时） */
  async acquire(timeoutMs = 30000): Promise<void> {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      if (this.tryAcquire()) return;
      // 等待到下一个补充周期
      const waitMs = Math.min(
        this.lastRefill + this.windowMs - Date.now() + 10,
        deadline - Date.now(),
      );
      if (waitMs <= 0) break;
      await new Promise(r => setTimeout(r, waitMs));
    }
    throw new AdapterError({
      message: `Rate limiter timeout after ${timeoutMs}ms`,
      category: 'RATE_LIMIT',
      adapterCode: 'rate_limiter',
    });
  }

  private refill() {
    const now = Date.now();
    const elapsed = now - this.lastRefill;
    if (elapsed >= this.windowMs) {
      this.tokens = this.maxRequests;
      this.lastRefill = now;
    }
  }
}
